"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/layout/Navbar";
import { Provider } from "react-redux";
import { store } from "../redux/store";
import ReduxProvider from "../redux/ReduxProvider";
import Footer from "../components/layout/Footer";
import { WatchLaterProvider } from "../context/WatchLaterContext";
import { usePathname } from "next/navigation";
import Drawer from "../components/layout/Drawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 const metadata: Metadata = {
  title: "qulinejb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  // Define pages where you DON'T want the drawer (like login)
  const isAuthPage = pathname.includes("/auth/login");
  return (
    <html lang="en">
      <body className="antialiased font-sans">
        <ReduxProvider>
          <WatchLaterProvider>
            <Navbar />

            <div className="flex">
              {/* Only show drawer if we are NOT on a login/auth page */}
              {!isAuthPage && (
                <aside className="w-64 fixed inset-y-0 left-0  z-10 ">
                  <Drawer />
                </aside>
              )}
              {/* Push content to the right only if drawer is visible */}
              <main className="flex-1 w-full">{children}</main>
            </div>

            <Footer />
          </WatchLaterProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}