import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/layout/Navbar";
import { Provider } from "react-redux";
import { store } from "../redux/store";
import ReduxProvider from "../redux/ReduxProvider";
import Footer from "../components/layout/Footer";
import { WatchLaterProvider } from "../context/WatchLaterContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "qulinejb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <WatchLaterProvider>
            <Navbar />
            {children}
            <Footer />
          </WatchLaterProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}